apiVersion: v1
kind: Service
metadata:  
  name: myapp-service
spec:
  selector:    
    app: myapp
    type: front-end
  type: NodePort
  ports:  
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
