---
apiVersion: v1
kind: Service
metadata:
  name: mydeploy-clusterip
  labels:
    name: mydeploy-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80       # Cluster IP
      targetPort: 80  # Application port
      protocol: TCP
      name: http
  selector:
    app: nginx