---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-pod-readerbinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: podreader
  namespace: default
roleRef:
  kind: Role
  name: podread
  apiGroup: rbac.authorization.k8s.io