apiVersion: apps/v1
kind: Deployment
metadata:
  name: label
spec:
  selector:
    matchLabels:
      app: label
  replicas: 10
  template:
    metadata:
      labels:
        app: label
    spec:
      containers:
        - name: label
          image: nginx
      nodeSelector:
         hw: good