apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-deploy
spec:
  selector:
    matchLabels:
      app: probe
  replicas: 1
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: apache
          image: 192.168.1.150:3000/dncs0725/60httpd
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: probe-svc
  labels:
    name: probe-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: probe
