---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-deploy
spec:
  selector:
    matchLabels:
      app: probe
  replicas: 3
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: apache
          image: 192.168.1.150:3000/dncs0725/60httpd
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
---
 
apiVersion: v1
kind: Service
metadata:
  name: probe-svc
  labels:
    name: probe-svc
spec:
  type: NodePort
  ports:
    - port: 80       # Cluster IP
      targetPort: 80  # Application port
      protocol: TCP
      name: http
  selector:
    app: probe
