---
apiVersion: v1
kind: Pod
metadata:
  name: configmap
  labels:
spec:
  containers:
    - name: configmap
      image: httpd
      ports:
        - name: web 
          containerPort: 80
          protocol: TCP