---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: getclusterinfo
spec:
  schedule: "55 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: getclusterinfo
            image: bitnami/kubectl
            command: ['/bin/bash', '-c', "/data/go.sh"]
            volumeMounts:
            - name: nfs-volume
              mountPath: /data
            - name: config
              mountPath: .kube/config
          nodeName: m1-k8s
          volumes:
          - name: nfs-volume
            nfs:
              path: /nfs
              server: w2-k8s
          - name: config
            hostPath:
              path: /tmp/config
              type: File
          restartPolicy: Never
